import "./globals.css";

export const metadata = {
    title: "Components Activity",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="pt-br">
            <head>
                <title>{metadata.title}</title>
                <meta name="description" content={metadata.description} />
            </head>
            <body className="root-layout">
                {children}
            </body>
        </html>
    );
}